### PR TITLE
Add method for generating signed Smart CDN URLs

### PR DESCRIPTION
**Pull request by Acconut**
We recently added support for signed Smart CDN URLs (see https://transloadit.com/docs/topics/signature-authentication/#smart-cdn) and would like our SDKs to offer methods for generating these signed URLs.

This PR adds such a method with tests.

### CODE REVIEW

**Comment by Acconut** [comment]
@cdr-chakotay Can you help me fix this linting error? https://github.com/transloadit/java-sdk/actions/runs/11974368156/job/33385298147#step:4:388

**Comment by cdr-chakotay** [comment]
> @cdr-chakotay Can you help me fix this linting error? https://github.com/transloadit/java-sdk/actions/runs/11974368156/job/33385298147#step:4:388

Sure! Will send you changes to circumvent this. (Need to get them uploaded from my IDE)

**Review by cdr-chakotay — APPROVED** [review]
I did now push the pending changes directly to circumvent the extra work:
- replaced wildcard imports
- dealt with trailing spaces
- dealt with line length issues

**Comment by Acconut** [comment]
Thank you very much!

**Pull request merged**
