### PR TITLE
Assembly addFields

### LINKED ISSUE #34: Add helper methods to add fields to assembly instructions
It'd nice if we had an `assembly.addField("field_name", "value")` method. This is more useful in Java since building assembly options can easily become quite cumbersome

### PR DESCRIPTION
**Pull request by cdr-chakotay**
Closes #34 
- added the methods addField() and addFields to Assembly.java
- wrote a JUnit test for the new methods.

### CODE REVIEW

**Review by cdr-chakotay — COMMENTED** [review]
Just some explanations

**Comment by cdr-chakotay** [comment]
I will change the arrangement of the methods to have it in the OptionsBuilder. As a result Assembly.class and Template.class would inherit the methods and variables. This would be helpful because both classes require the feature.

**Comment by cdr-chakotay** [comment]
There is still an issue with Fields in Templates. Maybe they are not supported by the API.

**Comment by cdr-chakotay** [comment]
Ready to merge if you are fine with that @Acconut :)

**Review by Acconut — APPROVED** [review]
Very nice work!

**Pull request merged**
